<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE language [
        <!ELEMENT language ANY>
        <!ELEMENT locale ANY>
        <!ELEMENT text (source,output)>
        <!ELEMENT source ANY>
        <!ELEMENT output ANY>
        <!ATTLIST language
                src       CDATA    #REQUIRED
                output    CDATA    #REQUIRED
                name      CDATA    #REQUIRED
                native    CDATA    #REQUIRED
                >
        <!ATTLIST locale
                region    CDATA    #REQUIRED
                name      CDATA    #REQUIRED
                native    CDATA    #REQUIRED
                >
        ]>
<language src="en" output="fr" name="French" native="Française">
    <locale region="FR" name="France" native="France">
        <text>
            <source>Forms</source>
            <output>Formulaires</output>
        </text>
        <text>
            <source>There are currently no forms.</source>
            <output>Il n'y a pas de formes.</output>
        </text>
        <text>
            <source>There are currently no form submissions.</source>
            <output>Il n'y a aucune soumission de formulaire.</output>
        </text>
        <text>
            <source>Method</source>
            <output>Méthode</output>
        </text>
        <text>
            <source>Use CAPTCHA</source>
            <output>Utilisez CAPTCHA</output>
        </text>
        <text>
            <source>Use CSRF</source>
            <output>Utilisez CSRF</output>
        </text>
        <text>
            <source>Subject</source>
            <output>Sujet</output>
        </text>
        <text>
            <source>Reply To</source>
            <output>Répondre</output>
        </text>
        <text>
            <source>Action</source>
            <output>Action</output>
        </text>
        <text>
            <source>Redirect</source>
            <output>Réorienter</output>
        </text>
        <text>
            <source>Form Attributes</source>
            <output>Attributs de formulaire</output>
        </text>
        <text>
            <source>Submit Value</source>
            <output>Envoyer Valeur</output>
        </text>
        <text>
            <source>Submit Attributes</source>
            <output>Envoyer Attributs</output>
        </text>
        <text>
            <source>That form name already exists. The name must be unique.</source>
            <output>Ce nom de formulaire existe déjà. Le nom doit être unique.</output>
        </text>
        <text>
            <source>That form does not exist.</source>
            <output>N'existe pas sous cette forme.</output>
        </text>
        <text>
            <source>Enter Code</source>
            <output>Entrez le code</output>
        </text>
    </locale>
</language>